/** @typedef {string} Color */

export const /** @type {Color} */ red = "#f91340"
export const /** @type {Color} */ orange = "darkorange"
export const /** @type {Color} */ yellow = "gold"
export const /** @type {Color} */ green = "greenyellow"
export const /** @type {Color} */ teal = "mediumseagreen"
export const /** @type {Color} */ blue = "deepskyblue"
export const /** @type {Color} */ purple = "mediumpurple"
export const /** @type {Color} */ pink = "hotpink"
export const /** @type {Color} */ white = "white"
export const /** @type {Color} */ light = "#f0f0f0"
export const /** @type {Color} */ silver = "#e0e0e0"
export const /** @type {Color} */ grey = "#3d3d3d"
export const /** @type {Color} */ dark = "#242424"
export const /** @type {Color} */ black = "black"
