export const CUBE_DUO_SPEED_MIN = 200
export const CUBE_DUO_SPEED_MAX = 250
export const CUBE_DUO_SPIN_MIN = Math.PI / 2.5
export const CUBE_DUO_SPIN_MAX = Math.PI / 1.5
export const CUBE_DUO_HP = 101
export const CUBE_DUO_COLLISION_DAMAGE = 13
export const CUBE_DUO_GUN_RELOAD_MIN = 2.6
export const CUBE_DUO_GUN_RELOAD_MAX = 3.4
export const CUBE_DUO_BULLET_SPEED = 800
export const CUBE_DUO_BULLET_DAMAGE = 9

export const CUBE_QUAD_SPEED_MIN = 200
export const CUBE_QUAD_SPEED_MAX = 250
export const CUBE_QUAD_SPIN_MIN = Math.PI / 2.5
export const CUBE_QUAD_SPIN_MAX = Math.PI / 1.5
export const CUBE_QUAD_HP = 123
export const CUBE_QUAD_COLLISION_DAMAGE = 19
export const CUBE_QUAD_GUN_RELOAD_MIN = 2.6
export const CUBE_QUAD_GUN_RELOAD_MAX = 3.4
export const CUBE_QUAD_BULLET_SPEED = 800
export const CUBE_QUAD_BULLET_DAMAGE = 13

export const CUBE_MISSILE_SPEED_MIN = 200
export const CUBE_MISSILE_SPEED_MAX = 250
export const CUBE_MISSILE_SPIN_MIN = Math.PI / 2.5
export const CUBE_MISSILE_SPIN_MAX = Math.PI / 1.5
export const CUBE_MISSILE_HP = 101
export const CUBE_MISSILE_COLLISION_DAMAGE = 13
export const CUBE_MISSILE_GUN_RELOAD_MIN = 3.2
export const CUBE_MISSILE_GUN_RELOAD_MAX = 4.8
export const CUBE_MISSILE_BULLET_SPEED = 800
export const CUBE_MISSILE_BULLET_STEER = Math.PI
export const CUBE_MISSILE_BULLET_DAMAGE = 11

export const AURA_SHIELD_HP = 97
export const AURA_SHIELD_COLLISION_DAMAGE = 13
export const AURA_SHIELD_FIELD_RELOAD = 5
export const AURA_SHIELD_FIELD_HP = 123
export const AURA_SHIELD_FIELD_HP_REGEN = 13

export const AURA_MEDIC_HP = 97
export const AURA_MEDIC_COLLISION_DAMAGE = 13
export const AURA_MEDIC_FIELD_RELOAD = 5
export const AURA_MEDIC_FIELD_HP = 123
export const AURA_MEDIC_FIELD_HP_REGEN = 13
export const AURA_MEDIC_FIELD_HEAL = 13

export const CRASHER_SPEED_MIN = 150
export const CRASHER_SPEED_MAX = 200
export const CRASHER_SPIN = 2 * Math.PI
export const CRASHER_HP = 101
export const CRASHER_COLLISION_DAMAGE = 17

export const CRASHER_SMART_SPEED_MIN = 150
export const CRASHER_SMART_SPEED_MAX = 200
export const CRASHER_SMART_SPIN = 2 * Math.PI
export const CRASHER_SMART_STEER = Math.PI / 4
export const CRASHER_SMART_HP = 101
export const CRASHER_SMART_COLLISION_DAMAGE = 17

export const DIV_SPEED_MIN = 150
export const DIV_SPEED_MAX = 200
export const DIV_SPIN_MIN = Math.PI / 3
export const DIV_SPIN_MAX = Math.PI / 2
export const DIV_HP = 101
export const DIV_COLLISION_DAMAGE = 13

export const DIV_SHARD_SPEED_MIN = 200
export const DIV_SHARD_SPEED_MAX = 250
export const DIV_SHARD_SPIN_MIN = Math.PI / 2
export const DIV_SHARD_SPIN_MAX = Math.PI / 1
export const DIV_SHARD_HP = 101
export const DIV_SHARD_COLLISION_DAMAGE = 13

export const TURRET_HP = 101
export const TURRET_COLLISION_DAMAGE = 13
export const TURRET_GUN_RELOAD_MIN = 2.6
export const TURRET_GUN_RELOAD_MAX = 3.4
export const TURRET_GUN_BULLET_SPEED = 800
export const TURRET_GUN_BULLET_DAMAGE = 9

export const TURRET_SMART_STEER = Math.PI
export const TURRET_SMART_HP = 101
export const TURRET_SMART_COLLISION_DAMAGE = 13
export const TURRET_SMART_GUN_RELOAD_MIN = 3.2
export const TURRET_SMART_GUN_RELOAD_MAX = 4.8
export const TURRET_SMART_GUN_BULLET_SPEED = 800
export const TURRET_SMART_GUN_BULLET_DAMAGE = 9

export const DRONE_ANY_STEER = 2 * Math.PI

export const DRONE_SPEED_MIN = 100
export const DRONE_SPEED_MAX = 200
export const DRONE_HP = 101
export const DRONE_COLLISION_DAMAGE = 13

export const DRONE_COMBAT_SPEED_MIN = 100
export const DRONE_COMBAT_SPEED_MAX = 200
export const DRONE_COMBAT_HP = 101
export const DRONE_COMBAT_COLLISION_DAMAGE = 13
export const DRONE_COMBAT_GUN_RELOAD_MIN = 3.2
export const DRONE_COMBAT_GUN_RELOAD_MAX = 4.8
export const DRONE_COMBAT_BULLET_SPEED = 800
export const DRONE_COMBAT_BULLET_DAMAGE = 9

export const DRONE_BOSS_SPEED = 100
export const DRONE_BOSS_HP = 101
export const DRONE_BOSS_COLLISION_DAMAGE = 13
export const DRONE_BOSS_GUN_RELOAD = 3
export const DRONE_BOSS_BULLET_SPEED = 800
export const DRONE_BOSS_BULLET_DAMAGE = 9

export const BOSS_MISSILE_SPEED = 200
export const BOSS_MISSILE_SPIN = Math.PI
export const BOSS_MISSILE_HP = 201
export const BOSS_MISSILE_COLLISION_DAMAGE = 13
export const BOSS_MISSILE_GUN_RELOAD = 3
export const BOSS_MISSILE_GUN_BULLET_SPEED = 800
export const BOSS_MISSILE_GUN_BULLET_DAMAGE = 9

export const BOSS_MISSILE_PROTEC_S_SPEED_MIN = 600
export const BOSS_MISSILE_PROTEC_S_SPEED_MAX = 700
export const BOSS_MISSILE_PROTEC_S_STEER_MIN = 2 * Math.PI
export const BOSS_MISSILE_PROTEC_S_STEER_MAX = 4 * Math.PI
export const BOSS_MISSILE_PROTEC_S_DAMAGE = 9

export const BOSS_MISSILE_PROTEC_L_SPEED_MIN = 400
export const BOSS_MISSILE_PROTEC_L_SPEED_MAX = 800
export const BOSS_MISSILE_PROTEC_L_STEER_MIN = 1 * Math.PI
export const BOSS_MISSILE_PROTEC_L_STEER_MAX = 3 * Math.PI
export const BOSS_MISSILE_PROTEC_L_DAMAGE = 13

export const PLAYER_HP = 101
export const PLAYER_COLLISION_DAMAGE = 23
export const PLAYER_ENERGY_WEAPON = 113
export const PLAYER_ENERGY_WEAPON_REGEN = 23
export const PLAYER_ENERGY_AUX = 113
export const PLAYER_ENERGY_AUX_REGEN = 23

export const PLAYER_TURRET_HP = 101
export const PLAYER_TURRET_COLLISION_DAMAGE = 23
export const PLAYER_TURRET_ENERGY_WEAPON = 113
export const PLAYER_TURRET_ENERGY_WEAPON_REGEN = 23
export const PLAYER_TURRET_ENERGY_AUX = 113
export const PLAYER_TURRET_ENERGY_AUX_REGEN = 23

export const PLAYER_GATLING_ANY_GUN_BULLET_SPEED = 800
export const PLAYER_GATLING_ANY_GUN_BULLET_DAMAGE = 9

export const PLAYER_GATLING_GUN_ENERGY = 9
export const PLAYER_GATLING_GUN_RELOAD = 0.13

export const PLAYER_GATLING_DOUBLE_GUN_ENERGY = 2 * PLAYER_GATLING_GUN_ENERGY
export const PLAYER_GATLING_DOUBLE_GUN_RELOAD = PLAYER_GATLING_GUN_RELOAD

export const PLAYER_MISSILE_GUN_ENERGY = 17
export const PLAYER_MISSILE_GUN_RELOAD = 0.27
export const PLAYER_MISSILE_GUN_BULLET_SPEED = 800
export const PLAYER_MISSILE_GUN_BULLET_STEER = Math.PI
export const PLAYER_MISSILE_GUN_BULLET_DAMAGE = 13

export const PLAYER_MISSILE_DOUBLE_GUN_ENERGY = PLAYER_MISSILE_GUN_ENERGY / 2
export const PLAYER_MISSILE_DOUBLE_GUN_RELOAD = PLAYER_MISSILE_GUN_RELOAD / 2
export const PLAYER_MISSILE_DOUBLE_GUN_BULLET_SPEED = 800
export const PLAYER_MISSILE_DOUBLE_GUN_BULLET_STEER = Math.PI
export const PLAYER_MISSILE_DOUBLE_GUN_BULLET_DAMAGE = PLAYER_MISSILE_GUN_BULLET_DAMAGE / 2

export const PLAYER_HOWITZER_GUN_ENERGY = 19
export const PLAYER_HOWITZER_GUN_RELOAD = 0.19
export const PLAYER_HOWITZER_GUN_BULLET_SPEED = 800
export const PLAYER_HOWITZER_GUN_BULLET_DAMAGE = 9

export const PLAYER_SHOCK_GUN_ENERGY = 19
export const PLAYER_SHOCK_GUN_RELOAD = 0.19
export const PLAYER_SHOCK_GUN_BULLET_SPEED = 700
export const PLAYER_SHOCK_GUN_BULLET_DAMAGE = 9

export const PLAYER_TURRET_GUN_ENERGY = 19
export const PLAYER_TURRET_GUN_RELOAD = 0.19
export const PLAYER_TURRET_GUN_BULLET_SPEED = 800
export const PLAYER_TURRET_GUN_BULLET_DAMAGE = 9

export const PLAYER_CHARGE_GUN_ENERGY = 17
export const PLAYER_CHARGE_GUN_RELOAD = 0

export const PLAYER_CHARGE_GUN_BULLET_S_CHARGE = 3
export const PLAYER_CHARGE_GUN_BULLET_S_SPEED_MIN = 400
export const PLAYER_CHARGE_GUN_BULLET_S_SPEED_MAX = 800
export const PLAYER_CHARGE_GUN_BULLET_S_DAMAGE = 9

export const PLAYER_CHARGE_GUN_BULLET_L_CHARGE = 7
export const PLAYER_CHARGE_GUN_BULLET_L_SPEED_MIN = 500
export const PLAYER_CHARGE_GUN_BULLET_L_SPEED_MAX = 700
export const PLAYER_CHARGE_GUN_BULLET_L_DAMAGE = 9

export const PLAYER_RESTORATION_ENERGY = 23
export const PLAYER_RESTORATION_REGEN = 11
export const PLAYER_RESTORATION_DURATION = 5

export const PLAYER_BERZERK_ENERGY = 17
export const PLAYER_BERZERK_DAMAGE_MULT = 2
export const PLAYER_BERZERK_DURATION = 5

export const PLAYER_SHOCKWAVE_ENERGY = 17
export const PLAYER_SHOCKWAVE_DAMAGE = 19
export const PLAYER_SHOCKWAVE_RADIUS = 307
export const PLAYER_SHOCKWAVE_TTL = 0.7

export const PLAYER_BOOST_HP = 17
export const PLAYER_BOOST_DAMAGE_PERCENT = 0.07
export const PLAYER_BOOST_WEAPON_RELOAD_PERCENT = 0.03
export const PLAYER_BOOST_WEAPON = 17
export const PLAYER_BOOST_WEAPON_REGEN = 11
export const PLAYER_BOOST_AUX = 17
export const PLAYER_BOOST_AUX_REGEN = 11
