type ClassyPartial<T> = Partial<T> & { class?: string }

declare namespace JSX {
	interface IntrinsicElements {
		[custom: string]: ClassyPartial<HTMLElement>

		a: ClassyPartial<HTMLAnchorElement>
		abbr: ClassyPartial<HTMLElement>
		address: ClassyPartial<HTMLElement>
		area: ClassyPartial<HTMLAreaElement>
		article: ClassyPartial<HTMLElement>
		aside: ClassyPartial<HTMLElement>
		audio: ClassyPartial<HTMLAudioElement>
		b: ClassyPartial<HTMLElement>
		base: ClassyPartial<HTMLBaseElement>
		bdi: ClassyPartial<HTMLElement>
		bdo: ClassyPartial<HTMLElement>
		big: ClassyPartial<HTMLElement>
		blockquote: ClassyPartial<HTMLElement>
		body: ClassyPartial<HTMLBodyElement>
		br: ClassyPartial<HTMLBRElement>
		button: ClassyPartial<HTMLButtonElement>
		canvas: ClassyPartial<HTMLCanvasElement>
		caption: ClassyPartial<HTMLElement>
		cite: ClassyPartial<HTMLElement>
		code: ClassyPartial<HTMLElement>
		col: ClassyPartial<HTMLTableColElement>
		colgroup: ClassyPartial<HTMLTableColElement>
		data: ClassyPartial<HTMLDataElement>
		datalist: ClassyPartial<HTMLDataListElement>
		dd: ClassyPartial<HTMLElement>
		del: ClassyPartial<HTMLElement>
		details: ClassyPartial<HTMLElement>
		dfn: ClassyPartial<HTMLElement>
		dialog: ClassyPartial<HTMLDialogElement>
		div: ClassyPartial<HTMLDivElement>
		dl: ClassyPartial<HTMLDListElement>
		dt: ClassyPartial<HTMLElement>
		em: ClassyPartial<HTMLElement>
		embed: ClassyPartial<HTMLEmbedElement>
		fieldset: ClassyPartial<HTMLFieldSetElement>
		figcaption: ClassyPartial<HTMLElement>
		figure: ClassyPartial<HTMLElement>
		footer: ClassyPartial<HTMLElement>
		form: ClassyPartial<HTMLFormElement>
		h1: ClassyPartial<HTMLHeadingElement>
		h2: ClassyPartial<HTMLHeadingElement>
		h3: ClassyPartial<HTMLHeadingElement>
		h4: ClassyPartial<HTMLHeadingElement>
		h5: ClassyPartial<HTMLHeadingElement>
		h6: ClassyPartial<HTMLHeadingElement>
		head: ClassyPartial<HTMLHeadElement>
		header: ClassyPartial<HTMLElement>
		hgroup: ClassyPartial<HTMLElement>
		hr: ClassyPartial<HTMLHRElement>
		html: ClassyPartial<HTMLHtmlElement>
		i: ClassyPartial<HTMLElement>
		iframe: ClassyPartial<HTMLIFrameElement>
		img: ClassyPartial<HTMLImageElement>
		input: ClassyPartial<HTMLInputElement>
		ins: ClassyPartial<HTMLModElement>
		kbd: ClassyPartial<HTMLElement>
		keygen: ClassyPartial<HTMLElement>
		label: ClassyPartial<HTMLLabelElement>
		legend: ClassyPartial<HTMLLegendElement>
		li: ClassyPartial<HTMLLIElement>
		link: ClassyPartial<HTMLLinkElement>
		main: ClassyPartial<HTMLElement>
		map: ClassyPartial<HTMLMapElement>
		mark: ClassyPartial<HTMLElement>
		menu: ClassyPartial<HTMLElement>
		menuitem: ClassyPartial<HTMLElement>
		meta: ClassyPartial<HTMLMetaElement>
		meter: ClassyPartial<HTMLElement>
		nav: ClassyPartial<HTMLElement>
		noindex: ClassyPartial<HTMLElement>
		noscript: ClassyPartial<HTMLElement>
		object: ClassyPartial<HTMLObjectElement>
		ol: ClassyPartial<HTMLOListElement>
		optgroup: ClassyPartial<HTMLOptGroupElement>
		option: ClassyPartial<HTMLOptionElement>
		output: ClassyPartial<HTMLElement>
		p: ClassyPartial<HTMLParagraphElement>
		param: ClassyPartial<HTMLParamElement>
		picture: ClassyPartial<HTMLElement>
		pre: ClassyPartial<HTMLPreElement>
		progress: ClassyPartial<HTMLProgressElement>
		q: ClassyPartial<HTMLQuoteElement>
		rp: ClassyPartial<HTMLElement>
		rt: ClassyPartial<HTMLElement>
		ruby: ClassyPartial<HTMLElement>
		s: ClassyPartial<HTMLElement>
		samp: ClassyPartial<HTMLElement>
		slot: ClassyPartial<HTMLSlotElement>
		script: ClassyPartial<HTMLScriptElement>
		section: ClassyPartial<HTMLElement>
		select: ClassyPartial<HTMLSelectElement>
		small: ClassyPartial<HTMLElement>
		source: ClassyPartial<HTMLSourceElement>
		span: ClassyPartial<HTMLSpanElement>
		strong: ClassyPartial<HTMLElement>
		style: ClassyPartial<HTMLStyleElement>
		sub: ClassyPartial<HTMLElement>
		summary: ClassyPartial<HTMLElement>
		sup: ClassyPartial<HTMLElement>
		table: ClassyPartial<HTMLTableElement>
		template: ClassyPartial<HTMLTemplateElement>
		tbody: ClassyPartial<HTMLTableSectionElement>
		td: ClassyPartial<HTMLTableDataCellElement>
		textarea: ClassyPartial<HTMLTextAreaElement>
		tfoot: ClassyPartial<HTMLTableSectionElement>
		th: ClassyPartial<HTMLTableHeaderCellElement>
		thead: ClassyPartial<HTMLTableSectionElement>
		time: ClassyPartial<HTMLElement>
		title: ClassyPartial<HTMLTitleElement>
		tr: ClassyPartial<HTMLTableRowElement>
		track: ClassyPartial<HTMLTrackElement>
		u: ClassyPartial<HTMLElement>
		ul: ClassyPartial<HTMLUListElement>
		var: ClassyPartial<HTMLElement>
		video: ClassyPartial<HTMLVideoElement>
		wbr: ClassyPartial<HTMLElement>

		svg: ClassyPartial<SVGSVGElement>
		animate: ClassyPartial<SVGElement>
		animateMotion: ClassyPartial<SVGElement>
		animateTransform: ClassyPartial<SVGElement>
		circle: ClassyPartial<SVGCircleElement>
		clipPath: ClassyPartial<SVGClipPathElement>
		defs: ClassyPartial<SVGDefsElement>
		desc: ClassyPartial<SVGDescElement>
		ellipse: ClassyPartial<SVGEllipseElement>
		feBlend: ClassyPartial<SVGFEBlendElement>
		feColorMatrix: ClassyPartial<SVGFEColorMatrixElement>
		feComponentTransfer: ClassyPartial<SVGFEComponentTransferElement>
		feComposite: ClassyPartial<SVGFECompositeElement>
		feConvolveMatrix: ClassyPartial<SVGFEConvolveMatrixElement>
		feDiffuseLighting: ClassyPartial<SVGFEDiffuseLightingElement>
		feDisplacementMap: ClassyPartial<SVGFEDisplacementMapElement>
		feDistantLight: ClassyPartial<SVGFEDistantLightElement>
		feDropShadow: ClassyPartial<SVGFEDropShadowElement>
		feFlood: ClassyPartial<SVGFEFloodElement>
		feFuncA: ClassyPartial<SVGFEFuncAElement>
		feFuncB: ClassyPartial<SVGFEFuncBElement>
		feFuncG: ClassyPartial<SVGFEFuncGElement>
		feFuncR: ClassyPartial<SVGFEFuncRElement>
		feGaussianBlur: ClassyPartial<SVGFEGaussianBlurElement>
		feImage: ClassyPartial<SVGFEImageElement>
		feMerge: ClassyPartial<SVGFEMergeElement>
		feMergeNode: ClassyPartial<SVGFEMergeNodeElement>
		feMorphology: ClassyPartial<SVGFEMorphologyElement>
		feOffset: ClassyPartial<SVGFEOffsetElement>
		fePointLight: ClassyPartial<SVGFEPointLightElement>
		feSpecularLighting: ClassyPartial<SVGFESpecularLightingElement>
		feSpotLight: ClassyPartial<SVGFESpotLightElement>
		feTile: ClassyPartial<SVGFETileElement>
		feTurbulence: ClassyPartial<SVGFETurbulenceElement>
		filter: ClassyPartial<SVGFilterElement>
		foreignObject: ClassyPartial<SVGForeignObjectElement>
		g: ClassyPartial<SVGGElement>
		image: ClassyPartial<SVGImageElement>
		line: ClassyPartial<SVGLineElement>
		linearGradient: ClassyPartial<SVGLinearGradientElement>
		marker: ClassyPartial<SVGMarkerElement>
		mask: ClassyPartial<SVGMaskElement>
		metadata: ClassyPartial<SVGMetadataElement>
		mpath: ClassyPartial<SVGElement>
		path: ClassyPartial<SVGPathElement>
		pattern: ClassyPartial<SVGPatternElement>
		polygon: ClassyPartial<SVGPolygonElement>
		polyline: ClassyPartial<SVGPolylineElement>
		radialGradient: ClassyPartial<SVGRadialGradientElement>
		rect: ClassyPartial<SVGRectElement>
		stop: ClassyPartial<SVGStopElement>
		switch: ClassyPartial<SVGSwitchElement>
		symbol: ClassyPartial<SVGSymbolElement>
		text: ClassyPartial<SVGTextElement>
		textPath: ClassyPartial<SVGTextPathElement>
		tspan: ClassyPartial<SVGTSpanElement>
		use: ClassyPartial<SVGUseElement>
		view: ClassyPartial<SVGViewElement>
	}
}
